version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: shortner_url
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  url-shortener:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/shortner_url?schema=public"
    depends_on:
      - db

volumes:
  postgres_data: